### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [linux-audit/audit-userspace#101]
Looks like a lot of changes have been made since last release. I think that it would be good to release new/updated code base :)

**Comment by stevegrubb** [comment]
Yes, the new release has been planned for a long time. The one thing that makes this 3.0 instead of 2.9 is container support. This support has been trying to land for 2 years and keeps getting pushed back for various reasons. However, it seems that we are really close to actually landing something that everyone agrees on. So, we need to give it a little more time. Meanwhile, feel free to use an alpha release or a git snapshot. I keep the audit repo in an always ready to use state.

**Comment by stevegrubb** [comment]
Closing this out. A new release will be made when container support lands.

**Comment by kloczek** [comment]
Still no new release :P

**Comment by stevegrubb** [comment]
The current plan is release 3.0 within 30 days without container support because it is intractability unresolved with no hope of going anywhere.

**Comment by pcmoore** [comment]
> ... intractability unresolved with no hope of going anywhere.

While Steve and I obviously differ on the prospects of the audit container ID work, I am very much in favor of Steve releasing an updated version of his userspace tools.

**Comment by kloczek** [comment]
Current snapshot of the audit is used in Fedora so IMO more or less it proven that that snapshot is usable and/or it is nothing wrong with current state of the code.

IMO whatever still needs to be done can be done after make new release :)

And of course better is make more releases with less modifications :P
