### ISSUE TITLE
FTBFS with GCC 10

### ISSUE THREAD

**Issue by bigon** [linux-audit/audit-userspace#123]
Hello,

audit FTBFS with GCC 10 with the following error:

> /usr/bin/ld: ausearch-lol.o:./debian/build/src/../../../src/ausearch-common.h:53: multiple definition of `event_node_list'; ausearch.o:./debian/build/src/../../../src/ausearch-common.h:53: first defined here

This is happening also with audit-3.0-alpha9

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957020

**Comment by stevegrubb** [comment]
Hi, thanks for reporting this. That said, I don't see what the problem is. There are only 3 places where event_node_list is. ausearch-options.c, aureport-options.c, and ausearch-common.h. In the .h file, it is an extern so that everyone can access the variable. Both .c files include it so they have the same common declaration. In no place should ausearch-options.o and aureport-options.o ever link to the same file. They would stomp on each other in more ways than this variable.

Do you see what the issue is?

**Comment by bigon** [comment]
If I'm adding `-fcommon` to the `CLFAGS` it's compiling fine.

This is described in the guide to port to GCC 10: https://gcc.gnu.org/gcc-10/porting_to.html

**Comment by stevegrubb** [comment]
OK, that was fixed by commit 017e6c6. There hasn't been a release since then, but there will probably be a new one in May,

**Comment by bigon** [comment]
OK the patch fixes the issues
