### ISSUE TITLE
auditd-plugins.5 manpage in wrong section

### ISSUE THREAD

**Issue by bigon** [linux-audit/audit-userspace#124]
Hello,

Looks like the auditd-plugins.5 manpage declares an other section (8) that the file name in its headers, both should match.

Section 5 is about "File formats and configuration files" and "8 System management commands".

I guess the correct section is 5 here?

**Comment by stevegrubb** [comment]
Hi, I'm not 100% sure what the exact question is. I just read through the auditd-plugins.5 file and it looks correct. I'm not sure which section 8 you are referring to and what might be in conflict. All that happened between audit2 and audit3 is the plugin dir moved from /etc/audisp/plugins.d/ to /etc/audit/plugins.d/  but, in auditd.conf, you can point it back to the original location if you really need to. There isn't a migration function and users would need to move any 3rd party files themselves. That shouldn't be a problem because I haven't really heard of any.
