### ISSUE TITLE
What is the recommended way of compressing audit logs?

### ISSUE THREAD

**Issue by Cropi** [linux-audit/audit-userspace#299]
I would like to be able to compress audit logs and know what is the recommended way to do that.

I tried to do that by introducing a cron job that takes care about file compression on a daily basis, when auditd is signaled to rotate the files. It works, but I have some doubts with this approach. Especially when I have ```max_log_file_action = ROTATE``` in the auditd configuration file. There is a risk when the system detects that the max file size limit has been reached, so auditd will try to rotate the logs but if by chance the cron job is scheduled to be executed at the same time, then collision can happen.

Is there a better(recommended) way to achieve log compression? If not, would you accept a patch for introducing a new configuration option to compress logs?

**Comment by stevegrubb** [comment]
The auditd daemon has never really had log compression on its roadmap. This is because it is in a race to empty the kernel's audit queue before it overflows. Also, when searching gigabytes of logs, people want responsive utilities. I don't know how integrating compression would affect the performance of either auditd or ausearch.

**Comment by stevegrubb** [comment]
Thanks for asking the question. File compression is not on the roadmap. If you wish to ask any other questions, reopen this or ask on the mail list. Closing this out.
