### ISSUE TITLE
Can not audit mount syscall for util-linux 2.39.1

### ISSUE THREAD

**Issue by yizhao1** [linux-audit/audit-userspace#325]
audit version: 3.1.2
util-linux version: 2.39.1
kernel version: 6.1.51

Steps:
audit rules:
$ cat /etc/audit/audit.rules 
-D
-b 320
-f 1
-e 1
-a always,exit -F arch=b64 -S mount -F uid=0 -k TEST-export

$ auditctl -l
-a always,exit -F arch=b64 -S mount -F uid=0 -F key=TEST-export

$ mount -t ramfs /dev/ram0 /mnt
$ ausearch -k TEST-export
no matches

This used to work on util-linux 2.38.1:
The result with same steps:

time->Thu Sep  7 08:40:35 2023
type=PROCTITLE msg=audit(1694076035.712:755): proctitle=6D6F756E74002D740072616D6673002F6465762F72616D30002F6D6E74
type=PATH msg=audit(1694076035.712:755): item=0 name="/mnt" inode=3141 dev=fd:00 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:mnt_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1694076035.712:755): cwd="/etc/audit"
type=SYSCALL msg=audit(1694076035.712:755): arch=c000003e syscall=165 success=yes exit=0 a0=55addc948660 a1=55addc948680 a2=55addc948640 a3=0 items=1 ppid=379 pid=409 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=ttyS0 ses=4294967295 comm="mount" exe="/bin/mount.util-linux" subj=root:sysadm_r:mount_t:s0-s15:c0.c1023 key="TEST-export"

**Comment by stevegrubb** [comment]
This is discoverable with the strace command. It appears that it is now using a bunch of new syscalls:

fsopen("ramfs", FSOPEN_CLOEXEC)
mkdir("/run/mount", 0755)
fsconfig(3, FSCONFIG_SET_STRING, "source", "/dev/ram0", 0)
fsconfig(3, FSCONFIG_CMD_CREATE, NULL, NULL, 0)
fsmount(3, FSMOUNT_CLOEXEC, 0)
move_mount(4, "", AT_FDCWD, "/mnt", MOVE_MOUNT_F_EMPTY_PATH)

I have no idea which one contains the equivalent information to the old way or why it was modified to do this (just guessing it's because of containers and namespaces).

auditctl -a always,exit -S fsconfig,fsmount,move_mount -F key=mount

Then running mount shows that fsconfig is not logging any strings. Fsmount doesn't say what was created. And move_mount doesn't have an origin but shows where it winds up. It also looks like I need to add some code to interpret the constants used as parameters to these 3 syscalls.

Best you can do is probably is to audit move_mount and the execution of the command mount.

**Comment by stevegrubb** [comment]
Interpretations were added for fsopen, fsmount, and move_mount. New issues were opened for fsconfig and fsopen on the kernel repo. Still need to add interpretations for fsconfig.

**Comment by stevegrubb** [comment]
Interpretations have been added. I don't think there is anything left to do for user space. With util-linux changing it's mount technique to the fs* family of function, auditing "mounts" is going to be more complicated.
