### ISSUE TITLE
-Wformat-y2k warnings

### ISSUE THREAD

**Issue by neheb** [linux-audit/audit-userspace#380]
GCC warns on usage of %x in the codebase.

**Comment by stevegrubb** [comment]
Where?

**Comment by neheb** [comment]
Everywhere honestly. I was going to make a patch but too many locations.

**Comment by Cropi** [comment]
I don't see the `-Wformat-y2k` option explicitly being used in the project. Can you provide what `Compiler flags` are you using? Also what warnings do you see.

**Comment by stevegrubb** [comment]
Had a couple minutes to look at this. With -Wformat=2, we get "‘%x’ yields only last 2 digits of year in some locales". %x is the preferred date representation for the current locale. If the locale prefers to have 2 digit years, should I do anything about that? I want the formatting to be localized so that it matches the norms wherever people are. I don't think we worry about this warning.

**Comment by stevegrubb** [comment]
Thanks for the report. But I think we're going to choose to not worry about this at this time.  Closing this.
