### ISSUE TITLE
BUG: ausearch does not reliably find nodes when date is specified

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-userspace#50]
Originally entered as linux-audit/audit-kernel#83 for more information, the problem report is copied below:

>Hi folks, maybe it's just me or there's something wrong with the way I search through events, but the >following command returned no matches:
>
>[root@MasterServer audit]# ausearch -i -ts '18/05/18' -hn Client-Machine | more
>However, if I search the logs for that date and grep "Client-Machine", this time I get (quite a lot of) results.
>
>[root@MasterServer audit]# ausearch -i -ts '18/05/18' | grep Client-Machine | more
>node=Client-Machine type=LOGIN msg=audit(18/05/18 00:00:01.364:894794) : pid=101815 uid=root subj=system_u:system_r:crond_t:s0-s0:c0.c1023 old-auid=unset auid=root tty=(none) old-ses=4294967295 >ses=72579 res=yes
>node=Client-Machine type=PROCTITLE msg=audit(18/05/18 00:00:01.362:894792) : proctitle=/usr/sbin/unix_chkpwd root chkexpiry
>node=Client-Machine type=PATH msg=audit(18/05/18 00:00:01.362:894792) : item=1 name=/lib64/ld-linux-x86-64.so.2 inode=8067 dev=fd:00 mode=file,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:ld_so_t:s0 objtype=NORMAL
>node=Client-Machine type=PATH msg=audit(18/05/18 00:00:01.362:894792) : item=0 name=/usr/sbin/unix_chkpwd inode=116424 dev=fd:00 mode=file,suid,755 ouid=root ogid=root rdev=00:00 >obj=system_u:object_r:chkpwd_exec_t:s0 objtype=NORMAL
>node=Client-Machine type=EXECVE msg=audit(18/05/18 00:00:01.362:894792) : argc=3 a0=/usr/sbin/unix_chkpwd a1=root a2=chkexpiry
>node=Client-Machine type=SYSCALL msg=audit(18/05/18 00:00:01.362:894792) : arch=x86_64 syscall=execve success=yes exit=0 a0=0x7ff7e82df3cd a1=0x7ffc385aced0 a2=0x7ff7e84e2388 a3=0x2 items=2 >ppid=101815 pid=101816 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=unix_chkpwd exe=/usr/sbin/unix_chkpwd subj=system_u:system_r:chkpwd_t:s0->s0:c0.c1023 key=rootcmd
>node=Client-Machine type=PROCTITLE msg=audit(18/05/18 00:00:01.364:894793) : proctitle=/usr/sbin/unix_chkpwd root chkexpiry
>node=Client-Machine type=PATH msg=audit(18/05/18 00:00:01.364:894793) : item=0 name=/etc/shadow inode=8388687 dev=fd:00 mode=file,000 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:shadow_t:s0 >objtype=NORMAL
>node=Client-Machine type=SYSCALL msg=audit(18/05/18 00:00:01.364:894793) : arch=x86_64 syscall=open success=yes exit=3 a0=0x7fc932407453 a1=O_RDONLY|O_CLOEXEC a2=0x1b6 a3=0x24 items=1 >ppid=101815 pid=101816 aui
>--More--
>
>A couple of things that come to mind:
>
>1 - Perhaps the date format I use is incorrect? The ausearch manual does not give any clear examples.
>2 - The node I am targeting has an hyphenated name, "Client-Machine"..perhaps that is a misleading name for a node?
>
>Thanks,

**Comment by stevegrubb** [comment]
The date format is whatever your locale is. You can check it with date "+%x". The -hn option matches against things that show up in addr or host fields. These don't always have a value and thus no matching opportunity. To locate records by originating host, then you would search using --node. This should find the records you are looking for.

**Comment by gbettayeb** [comment]
@stevegrubb 
I made sure the date was set correctly before raising the bug:
[root@svpl-vlp-log01 audit]# date "+%x"
29/05/18
[root@svpl-vlp-log01 audit]# date
Tue 29 May 11:50:02 BST 2018

Since I raised the issue, I noticed that I already switched to the -n (--node) option and the outcome is the same.

I confirm this issue is still ongoing and is only impacting one single node consistently.

Also, very important point, the command runs fine when executed from a standard shell prompt:

[user@server audit]# /sbin/ausearch -i --input-logs -ts yesterday -n $server --just-one | grep $server
node=[###masking node name###] type=LOGIN msg=audit(28/05/18 00:00:01.223:1015756) : pid=41019 uid=root subj=system_u:system_r:crond_t:s0-s0:c0.c1023 old-auid=unset auid=root tty=(none) old-ses=4293168137 ses=87247 res=yes

however when the exact same code runs via a cron script, this particular node fails while all the other nodes can be retrieved just fine.

Thanks

**Comment by stevegrubb** [comment]
ausearch and report look at stdin to see if its a pipe. If so, it takes input from the pipe. cron presents a pipe to ausearch for stdin; a shell does not. So, to force input to be from the logs rather than stdin for cron, you need to also add --input-logs to the command line. After that, it should work fine.

**Comment by gbettayeb** [comment]
I am actually already using --input-logs with cron (see previous message), but it doesn't seem to make any difference.

**Comment by stevegrubb** [comment]
I don't know of any problem that causes this to work fine from the command prompt and not from a cron script when --input-logs is given for both. That said, are all the systems time sync'ed with an external source via NTP? Have you tried running the ausearch with --debug added? (This outputs information about malformed records.) What version of audit are you using?

**Comment by stevegrubb** [comment]
Maybe the locale information in the cron script is missing or different? Maybe the locale variables should be set in the script?

**Comment by stevegrubb** [comment]
I am closing this issue. If you have more information to provide, feel free to reopen the issue. I suspect the locale needs to be set in the cron script.
