### ISSUE TITLE
auserch expressions

### ISSUE THREAD

**Issue by dimv36** [linux-audit/audit-userspace#52]
Hi, I use libaudit library 2.6.7 on Debian Stretch.

I have a question for using Python binding (2.7). I want to search events via API search_add_expression() function based on exe path.

So, I wrote:

> parser.search_add_expression('exe i= /usr/sbin/cupsd', AUSEARCH_RULE_AND)

but I have exception

> EnvironmentError: Value expected, got `/usr/'

I change this to:

> parser.search_add_expression('exe i= "/usr/sbin/cupsd"', AUSEARCH_RULE_AND)

and my program crash with errcode 245 (echo $?)

What's wrong? Thank you!

**Comment by dimv36** [comment]
Problem was solved by installing auditd 2.8.3

**Comment by stevegrubb** [comment]
Good to know that it's fixed. The latest 2.8.4 audit package also corrects some other issues discovered in the auparse_search API. The only thing that I was going to suggest is that you add the \" escape sequence to the file name that you are searching for. IOW, something like this:

parser.search_add_expression('exe i= \"/usr/sbin/cupsd\"', AUSEARCH_RULE_AND)

If the problem was solved by upgrading, then I think we close this issue.

**Comment by dimv36** [comment]
Yes, I wrote as you said. Thanks!
