### ISSUE TITLE
I could not login to system after audit lib updated and reset selinux 

### ISSUE THREAD

**Issue by mikechiuP** [linux-audit/audit-userspace#68]
I suffer a strange issue.

Reproduce steps
1. install centos7.3 with minimal install.
2. update selinux to disabled and reboot system.
3. yum intall audit to update audit lib.
4. update selinux to enable selinux to enforcing and reboot

Issue: console display libaudit.so.1 permission denied and could not login again.
I need to use rescue mode to login and disabled selinux again.

libaudit version after update: 2.8.1-3.el7_5.1

I have no idea about this issue and guess that's because update audit with selinux disabled,
after enforcing, libaudit without, I don't know, but some types of selinux, makes other service like 
login, ..., etc could not refer to libaudit shared lib. ?

So do I need to update to newer version like 3.0 or ...?

Another discovery is /etc/audit/rules.d.
If I install with selinux disabled, some file under this folder will lack of selinux context.
I think whether the selinux on of off, the audit rules under /etc/audit must be with selinux context ?

The another problem is, since auditd should limited by selinux, and selinux need to send log to auditd,
this seems like a ref. loop and auditd need to have permission prior to selinux !?

Is there any tips about this situation?

**Comment by pcmoore** [comment]
The permission denial is likely because you put SELinux in disabled mode and then later re-enabled it.  If for some reason you need to bypass the SELinux access controls, the recommended way is to put SELinux in permissive mode, **not** disabled mode.  The problem is that in disabled mode SELinux is not running and does not have the ability to ensure any persistent objects on the system (e.g. files) are labeled correctly.

At this point you likely need to run the following command, as root, and then reboot, to force your system to relabel the entire filesystem:

    # touch /.autorelabel

**Comment by mikechiuP** [comment]
@pcmoore  Thanks for your answer!

The workaround we use is like what you suggest.

```
1. Change SELinux to permissive mode
2. Reboot system to make SELinux status work
3. Update audit and audit-lib
4. Change SELinux to disabled mode (original status)
5. reboot to make SELinux status work
```

Thanks for your reply!
